// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgHJvSHHTYf7l_nvZZli4apIm4lLbfpnc',
    appId: '1:506583199244:web:cfe2bbeb84be4cf4b40829',
    messagingSenderId: '506583199244',
    projectId: 'flutter-test-1031a',
    authDomain: 'flutter-test-1031a.firebaseapp.com',
    storageBucket: 'flutter-test-1031a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3oCqsfNPwY0PKuQHJ4jGZxYOK5O2T_Uw',
    appId: '1:506583199244:android:518e69b6644b6c11b40829',
    messagingSenderId: '506583199244',
    projectId: 'flutter-test-1031a',
    storageBucket: 'flutter-test-1031a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLUXrNe8OsfVDvP74rKYzMMrCeXRzfG8s',
    appId: '1:506583199244:ios:28a0575513000588b40829',
    messagingSenderId: '506583199244',
    projectId: 'flutter-test-1031a',
    storageBucket: 'flutter-test-1031a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLUXrNe8OsfVDvP74rKYzMMrCeXRzfG8s',
    appId: '1:506583199244:ios:28a0575513000588b40829',
    messagingSenderId: '506583199244',
    projectId: 'flutter-test-1031a',
    storageBucket: 'flutter-test-1031a.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}